# Generated by Django 4.2.4 on 2023-08-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_critique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critique',
            old_name='headline',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='uploader',
        ),
        migrations.RemoveField(
            model_name='critique',
            name='body',
        ),
        migrations.AddField(
            model_name='critique',
            name='content',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='critique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='critique',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='critique',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews_app.ticket'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
