# Generated by Django 4.2.4 on 2023-08-21 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0004_remove_critique_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critique',
            old_name='title',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='critique',
            name='content',
        ),
        migrations.RemoveField(
            model_name='critique',
            name='image',
        ),
        migrations.RemoveField(
            model_name='critique',
            name='starred',
        ),
        migrations.AddField(
            model_name='critique',
            name='body',
            field=models.TextField(blank=True, max_length=8192),
        ),
        migrations.AddField(
            model_name='critique',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, max_length=1024, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='critique',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews_app.ticket'),
        ),
    ]
