# Generated by Django 4.2.4 on 2023-08-23 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews_app', '0007_rename_headline_critique_commentaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critique',
            name='user',
        ),
        migrations.CreateModel(
            name='CritiqueContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.CharField(blank=True, max_length=255)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('critique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews_app.critique')),
            ],
        ),
        migrations.AddField(
            model_name='critique',
            name='contributor',
            field=models.ManyToManyField(through='reviews_app.CritiqueContributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
