# Generated by Django 4.2.4 on 2023-08-23 08:32

from django.db import migrations


def migrate_author_to_contributors(apps, schema_editor):
    Critique = apps.get_model('reviews_app', 'Critique')
    for critique in Critique.objects.all():
        if critique.author:
            critique.contributors.add(
                critique.author, through_defaults={'contribution': 'Auteur principal'})


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0009_critique_author_alter_critique_contributor'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_contributors)
    ]
