# Generated by Django 4.2.4 on 2023-08-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0010_auto_20230823_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critique',
            old_name='contributor',
            new_name='contributors',
        ),
    ]
