# Generated by Django 4.2.4 on 2023-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0011_rename_contributor_critique_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='has_critique',
            field=models.BooleanField(default=False),
        ),
    ]
