# Generated by Django 4.2.4 on 2023-09-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0012_ticket_has_critique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critique',
            name='note',
            field=models.PositiveIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')]),
        ),
        migrations.AlterField(
            model_name='critique',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='critiques', to='reviews_app.ticket'),
        ),
    ]
